base_url = "https://implicit.computer"

title = "Implicit Dot Computer"
author = "keaton"
description = 'you can visit it on the "web", a "web" "site" if you will.'
minify_html = true

generate_feeds = true
feed_filenames = ["atom.xml"]
default_language = "en"
build_search_index = true

[markdown]
definition_list = true

[markdown.highlighting]
style = "inline"
dark_theme = "gruvbox-dark-medium"
light_theme = "gruvbox-light-hard"
error_on_missing_langauges = true


[[taxonomies]] 
name = "tags"
feed = false

[extra]
header_nav = [
{ name = "about", url = "/about"},
{ name = "posts", url = "/blog"},
{ name = "notes", url = "/notes" },
{name = "feeds", url = "/feeds"},
{name = "blogroll", url = "/feeds.opml.xml"}
]

